/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author fer
 */
public class InterfazFacturacionVentaRegistro extends javax.swing.JPanel {

    /**
     * Creates new form InterfazFacturacionRegistroVenta
     */
    public InterfazFacturacionVentaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtClienteRegistroEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClienteRegistroTelefono = new javax.swing.JTextField();
        txtClienteRegistroDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnClienteRegistroGuardar = new javax.swing.JButton();
        txtClienteRegistroNombre = new javax.swing.JTextField();
        btnClienteRegistroEiminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnFacturacionRegistroVentaBuscarRepuesto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFacturacionRegistroVentaListaRepuesto = new javax.swing.JTable();
        txtFacturacionRegistroVentaMontoTotal = new javax.swing.JTextField();
        btnFacturacionRegistroVentaSumarPedido = new javax.swing.JButton();
        txtFacturacionRegistroVentaBuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnFacturacionRegistroVentaBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnFacturacionRegistroVentaTomar = new javax.swing.JButton();
        txtFacturacionRegistroVentaBuscarRepuesto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnFacturacionRegistroVentaAnular = new javax.swing.JButton();
        btnFacturacionRegistroVentaRegresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFacturacionRegistroVentaListaPedido = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        btnFacturacionRegistroVentaAnadir = new javax.swing.JButton();
        btnFacturacionRegistroVentaRestarItem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtClienteRegistroEmail1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFacturacionRegistroVentaTelefono = new javax.swing.JTextField();
        txtFacturacionRegistroVentaDireccion = new javax.swing.JTextField();
        txtFacturacionRegistroVentaTipoDoc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnFacturacionRegistroVentaGuardar = new javax.swing.JButton();
        txtFacturacionRegistroVentaNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));

        jLabel2.setText("Email");

        txtClienteRegistroEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRegistroEmailActionPerformed(evt);
            }
        });

        jLabel3.setText("Teléfono");

        txtClienteRegistroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRegistroTelefonoActionPerformed(evt);
            }
        });

        txtClienteRegistroDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRegistroDireccionActionPerformed(evt);
            }
        });

        jLabel4.setText("Dirección");

        btnClienteRegistroGuardar.setText("Guardar");
        btnClienteRegistroGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteRegistroGuardarActionPerformed(evt);
            }
        });

        txtClienteRegistroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRegistroNombreActionPerformed(evt);
            }
        });

        btnClienteRegistroEiminar.setText("Eliminar");

        jLabel1.setText("Nombres y apellidos//Nombre empresa");

        btnFacturacionRegistroVentaBuscarRepuesto.setText("Buscar codigo/proveedor");

        tbFacturacionRegistroVentaListaRepuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código de repuesto", "Nombre de repuesto", "Marca", "Unidad", "Proveedor", "Costo unitario", "Cantidad disponible"
            }
        ));
        jScrollPane2.setViewportView(tbFacturacionRegistroVentaListaRepuesto);

        btnFacturacionRegistroVentaSumarPedido.setText("Sumar pedido");

        jLabel5.setText("Código de venta");

        btnFacturacionRegistroVentaBuscar.setText("Buscar");
        btnFacturacionRegistroVentaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionRegistroVentaBuscarActionPerformed(evt);
            }
        });

        jLabel8.setText("Repuestos en tienda");

        btnFacturacionRegistroVentaTomar.setText("Tomar pedido");

        txtFacturacionRegistroVentaBuscarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturacionRegistroVentaBuscarRepuestoActionPerformed(evt);
            }
        });

        jLabel6.setText("Monto Total");

        btnFacturacionRegistroVentaAnular.setText("Anular pedido");

        btnFacturacionRegistroVentaRegresar.setText("Regresar");

        jLabel7.setText("Pedido del cliente");

        tbFacturacionRegistroVentaListaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código de repuesto", "Nombre de repuesto", "Marca", "Unidad", "Proveedor", "Costo unitario", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tbFacturacionRegistroVentaListaPedido);

        btnFacturacionRegistroVentaAnadir.setText("Añadir item");

        btnFacturacionRegistroVentaRestarItem.setText("Restar pedido");
        btnFacturacionRegistroVentaRestarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionRegistroVentaRestarItemActionPerformed(evt);
            }
        });

        jButton1.setText("DNI/RUT");

        jLabel9.setText("Email");

        txtClienteRegistroEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRegistroEmail1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Teléfono");

        txtFacturacionRegistroVentaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturacionRegistroVentaTelefonoActionPerformed(evt);
            }
        });

        txtFacturacionRegistroVentaDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturacionRegistroVentaDireccionActionPerformed(evt);
            }
        });

        jLabel11.setText("Dirección");

        btnFacturacionRegistroVentaGuardar.setText("Guardar");
        btnFacturacionRegistroVentaGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionRegistroVentaGuardarActionPerformed(evt);
            }
        });

        txtFacturacionRegistroVentaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturacionRegistroVentaNombreActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombres y apellidos//Nombre empresa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFacturacionRegistroVentaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(48, 48, 48)
                                .addComponent(txtFacturacionRegistroVentaTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFacturacionRegistroVentaNombre)
                            .addComponent(txtClienteRegistroEmail1)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFacturacionRegistroVentaGuardar))
                            .addComponent(txtFacturacionRegistroVentaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFacturacionRegistroVentaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFacturacionRegistroVentaBuscar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFacturacionRegistroVentaBuscarRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFacturacionRegistroVentaBuscarRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnFacturacionRegistroVentaAnular)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnFacturacionRegistroVentaTomar))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFacturacionRegistroVentaAnadir, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(btnFacturacionRegistroVentaRestarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnFacturacionRegistroVentaSumarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtFacturacionRegistroVentaMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFacturacionRegistroVentaRegresar)
                                .addGap(11, 11, 11)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 918, Short.MAX_VALUE)
                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(btnFacturacionRegistroVentaBuscarRepuesto)
                                            .addComponent(txtFacturacionRegistroVentaBuscarRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnFacturacionRegistroVentaRegresar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(btnFacturacionRegistroVentaAnadir)
                                .addGap(18, 32, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(244, 244, 244))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(342, 342, 342)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFacturacionRegistroVentaRestarItem)
                                    .addComponent(btnFacturacionRegistroVentaSumarPedido)
                                    .addComponent(txtFacturacionRegistroVentaMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFacturacionRegistroVentaAnular)
                            .addComponent(btnFacturacionRegistroVentaTomar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFacturacionRegistroVentaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFacturacionRegistroVentaBuscar))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFacturacionRegistroVentaTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(19, 19, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacturacionRegistroVentaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClienteRegistroEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacturacionRegistroVentaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacturacionRegistroVentaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnFacturacionRegistroVentaGuardar)))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturacionRegistroVentaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionRegistroVentaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturacionRegistroVentaBuscarActionPerformed

    private void txtFacturacionRegistroVentaBuscarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturacionRegistroVentaBuscarRepuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturacionRegistroVentaBuscarRepuestoActionPerformed

    private void btnFacturacionRegistroVentaRestarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionRegistroVentaRestarItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturacionRegistroVentaRestarItemActionPerformed

    private void txtClienteRegistroEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRegistroEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRegistroEmailActionPerformed

    private void txtClienteRegistroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRegistroTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRegistroTelefonoActionPerformed

    private void txtClienteRegistroDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRegistroDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRegistroDireccionActionPerformed

    private void btnClienteRegistroGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteRegistroGuardarActionPerformed

    }//GEN-LAST:event_btnClienteRegistroGuardarActionPerformed

    private void txtClienteRegistroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRegistroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRegistroNombreActionPerformed

    private void txtClienteRegistroEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRegistroEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRegistroEmail1ActionPerformed

    private void txtFacturacionRegistroVentaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturacionRegistroVentaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturacionRegistroVentaTelefonoActionPerformed

    private void txtFacturacionRegistroVentaDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturacionRegistroVentaDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturacionRegistroVentaDireccionActionPerformed

    private void btnFacturacionRegistroVentaGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionRegistroVentaGuardarActionPerformed

    }//GEN-LAST:event_btnFacturacionRegistroVentaGuardarActionPerformed

    private void txtFacturacionRegistroVentaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturacionRegistroVentaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturacionRegistroVentaNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClienteRegistroEiminar;
    public javax.swing.JButton btnClienteRegistroGuardar;
    public javax.swing.JButton btnFacturacionRegistroVentaAnadir;
    public javax.swing.JButton btnFacturacionRegistroVentaAnular;
    public javax.swing.JButton btnFacturacionRegistroVentaBuscar;
    public javax.swing.JButton btnFacturacionRegistroVentaBuscarRepuesto;
    public javax.swing.JButton btnFacturacionRegistroVentaGuardar;
    public javax.swing.JButton btnFacturacionRegistroVentaRegresar;
    public javax.swing.JButton btnFacturacionRegistroVentaRestarItem;
    public javax.swing.JButton btnFacturacionRegistroVentaSumarPedido;
    public javax.swing.JButton btnFacturacionRegistroVentaTomar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tbFacturacionRegistroVentaListaPedido;
    public javax.swing.JTable tbFacturacionRegistroVentaListaRepuesto;
    public javax.swing.JTextField txtClienteRegistroDireccion;
    public javax.swing.JTextField txtClienteRegistroEmail;
    public javax.swing.JTextField txtClienteRegistroEmail1;
    public javax.swing.JTextField txtClienteRegistroNombre;
    public javax.swing.JTextField txtClienteRegistroTelefono;
    public javax.swing.JTextField txtFacturacionRegistroVentaBuscar;
    public javax.swing.JTextField txtFacturacionRegistroVentaBuscarRepuesto;
    public javax.swing.JTextField txtFacturacionRegistroVentaDireccion;
    public javax.swing.JTextField txtFacturacionRegistroVentaMontoTotal;
    public javax.swing.JTextField txtFacturacionRegistroVentaNombre;
    public javax.swing.JTextField txtFacturacionRegistroVentaTelefono;
    public javax.swing.JTextField txtFacturacionRegistroVentaTipoDoc;
    // End of variables declaration//GEN-END:variables
}
