/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author fer
 */
public class InterfazClienteRegistro extends javax.swing.JPanel {

    /**
     * Creates new form Interfaz_RegistrarCliente
     */
    public InterfazClienteRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClienteRegistroBuscar = new javax.swing.JButton();
        btnClienteRegistroRegresar = new javax.swing.JButton();
        txtClienteRegistroNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtClienteRegistroEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClienteRegistroTelefono = new javax.swing.JTextField();
        txtClienteRegistroDireccion = new javax.swing.JTextField();
        txtClienteRegistroTipoDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnClienteRegistroGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnClienteRegistroEiminar = new javax.swing.JButton();
        btnClienteRegistroTipoDocumento = new javax.swing.JButton();

        btnClienteRegistroBuscar.setText("Buscar");

        btnClienteRegistroRegresar.setText("Regresar");

        txtClienteRegistroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRegistroNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombres y apellidos//Nombre empresa");

        jLabel2.setText("Email");

        txtClienteRegistroEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRegistroEmailActionPerformed(evt);
            }
        });

        jLabel3.setText("Teléfono");

        txtClienteRegistroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRegistroTelefonoActionPerformed(evt);
            }
        });

        txtClienteRegistroDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRegistroDireccionActionPerformed(evt);
            }
        });

        jLabel4.setText("Dirección");

        btnClienteRegistroGuardar.setText("Guardar");
        btnClienteRegistroGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteRegistroGuardarActionPerformed(evt);
            }
        });

        btnClienteRegistroEiminar.setText("Eliminar");

        btnClienteRegistroTipoDocumento.setText("DNI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(534, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClienteRegistroBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClienteRegistroRegresar))
                    .addComponent(jSeparator1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClienteRegistroTipoDocumento)
                        .addGap(26, 26, 26)
                        .addComponent(txtClienteRegistroTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtClienteRegistroNombre)
                    .addComponent(txtClienteRegistroEmail)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btnClienteRegistroEiminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClienteRegistroGuardar))
                    .addComponent(txtClienteRegistroDireccion)
                    .addComponent(txtClienteRegistroTelefono))
                .addGap(453, 453, 453))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteRegistroBuscar)
                    .addComponent(btnClienteRegistroRegresar))
                .addGap(48, 48, 48)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteRegistroTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteRegistroTipoDocumento))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClienteRegistroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClienteRegistroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClienteRegistroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClienteRegistroDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteRegistroGuardar)
                    .addComponent(btnClienteRegistroEiminar))
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteRegistroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRegistroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRegistroNombreActionPerformed

    private void txtClienteRegistroEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRegistroEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRegistroEmailActionPerformed

    private void txtClienteRegistroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRegistroTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRegistroTelefonoActionPerformed

    private void txtClienteRegistroDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRegistroDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRegistroDireccionActionPerformed

    private void btnClienteRegistroGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteRegistroGuardarActionPerformed

    }//GEN-LAST:event_btnClienteRegistroGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClienteRegistroBuscar;
    public javax.swing.JButton btnClienteRegistroEiminar;
    public javax.swing.JButton btnClienteRegistroGuardar;
    public javax.swing.JButton btnClienteRegistroRegresar;
    public javax.swing.JButton btnClienteRegistroTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField txtClienteRegistroDireccion;
    public javax.swing.JTextField txtClienteRegistroEmail;
    public javax.swing.JTextField txtClienteRegistroNombre;
    public javax.swing.JTextField txtClienteRegistroTelefono;
    public javax.swing.JTextField txtClienteRegistroTipoDocumento;
    // End of variables declaration//GEN-END:variables
}
